"""Added order field to Ca3434343e

Revision ID: 897ea1b86ba2
Revises: 2a3d8863f1f7
Create Date: 2024-04-03 19:32:13.875947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897ea1b86ba2'
down_revision = '2a3d8863f1f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('category_order_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint('category_order_key', ['order'])

    # ### end Alembic commands ###
